spring.application.name=user-jiro
springdoc.swagger-ui.path=/swagger-ui
server.port=8087

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/jiro_user
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}

app.url=http://localhost:8086/api/v2