spring.application.name=user-jiro
springdoc.swagger-ui.path=/swagger-ui
server.port=8085

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/user-jiro
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}